name: Aerplane game workflow

on: 
  push:
    branches: ["main"]
    workflow_dispatch:

    permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs: 
  deploy: enviroment:
    name: github-pages
    url: ${{ steps.deployment.output.page_url}}
  runs-on: ubuntu-latest
  steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/comfigure-pages@5
    - name: Upload artifcat
      uses: actions/upload-pages-artifact@v3
  
      



  
